#######################################################################################
#
#       Welcome to Peligon Authentication's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonChat/Lang/' to see the supported languages.
  Language File: "en_US"
  database: "SQLite"

# This will automatically check for updates
check-for-updates: true