name: PeligonAuthentication
version: '${project.version}'
main: net.peligon.PeligonAuthentication.Main
api-version: 1.13
authors: [ darkwinged ]
description: This is an open-source plugin
commands:
  authentication:
    aliases:
      - auth
    description: Allows administrators to reset Google Auth tokens