#######################################################################################
#
#       Welcome to Peligon LifeSteal's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonLifeSteal/Lang/' to see the supported languages.
  lang: "en_US"
  # Available options: "MySQL", "SQLite"
  database: "SQLite"
  MySQL:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""

###############################################################
# +---------------------------------------------------------+ #
# |                Peligon LifeSteal (Events)               | #
# |    !!! To disable modules, add # before to item !!!     | #
# +---------------------------------------------------------+ #
###############################################################
Events:
  # These two settings are protected by permissions.
  # Permissions: "Peligon.LifeSteal.Keep.Inventory", "Peligon.LifeSteal.Keep.Experience"
  #  - keep-inventory
  #  - keep-experience
  - lightning-strike-on-death
  - death-penalty
  #  - commands-on-death
  # Only allow players to take away lives.
  #  - players-only
  #  - auto-respawn
  - custom-death-messages
  #  - combat-log
  - death-chest
  #  - damage-indicator
  - health-indicator
  - bounties

# What happens to the player after death
After-Life:
  ban-user:
    enabled: true
    message: "You have died but there is still hope. Try and get someone to revive you."
  teleport-user:
    enabled: false
    message: "You have died but there is still hope. Try and get someone to revive you."
    world: "world"

# What happens when a player respawns.
Player-Respawn:
  title:
    send-title: true
    has-lives-left:
      title: "&7%player%"
      subtitle: "&cYou have &e%lives% &clives left!"
    no-lives-left:
      title: "&7%player%"
      subtitle: "&cYou have no lives left!"
    fade-in: 20
    stay: 60
    fade-out: 20

# Add an effect to the player when they die.
Lightning-on-death:
  only-players: false
  # Only execute lightning when the player reaches a certain amount of lives.
  # -1 means execute lightning on death regardless of lives.
  execute-at-lives: -1

# How much a player's bounty increases when they kill a player.
Bounties:
  # How many players do they need to kill before the bounty starts to increase.
  minimum-kill-streak: 3
  bounty-per-kill: 100





















combat-tag:
  blocked-commands:
    - "spawn"
    - "warp"
    - "home"
  # How long should the combat tag be active for
  # !! This is in seconds.
  duration: 30

blacklisted-mobs:
  - "ENDERMAN"
  - "ENDERMITE"
  - "PHANTOM"

Commands-on-Death:
  # Only execute commands when the player reaches a certain amount of lives.
  execute-at-lives: 0
  commands:
    - "say &c%player% has just died! They have %lives% lives left!"
    - "say Second message!"

# What will be executed when the player runs out of lives.
Out-of-Lives:
  Actions:
    - ban-on-death
    - kick-on-death
    - change-gamemode-on-death
    - teleport-player-world
  Settings:
    gamemode: SPECTATOR
    world: "world"

# If the player dies the amount will be removed from their bank.
Death-Penalty:
  only-players: false
  amount: 100

# When a player dies their items will be placed in an inventory for them to pick up.
Death-Chest:
  block: SEA_LANTERN
  inventory-name: "&e%player%'s &7Grave"
  hologram: true
  hologram-text: "&e%player%'s &cGrave"

# Show how much damage a player is dealing.
Damage-Indicator:
  only-players: false
  text: "&c%damage%"
  length: 2

# This will automatically check for updates
check-for-updates: true