#######################################################################################
#
#       Welcome to Peligon LifeSteal's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonLifeSteal/Lang/' to see the supported languages.
  Language File: "en_US"
  database: "SQLite"
  starting-lives: 5

# Settings for how the player will lose a life.
Lose-Lives:
  # Only allow players to take lives away.
  players-only: false
  blacklisted-mobs:
    - "ENDERMAN"
    - "ENDERMITE"
    - "PHANTOM"

# What happens when a player respawns.
Player-Respawn:
  title:
    send-title: true\
    has-lives-left:
      title: "&7%player%"
      subtitle: "&cYou have &e%lives% &clives left!"
    no-lives-left:
      title: "&7%player%"
      subtitle: "&cYou have no lives left!"
    fade-in: 20
    stay: 60
    fade-out: 20

# Commands to be executed when a player reaches a chosen amount of lives.
Commands-on-Death:
  enabled: false
  # Only execute commands when the player reaches a certain amount of lives.
  execute-at-lives: 0
  commands:
    - "say &c%player% has just died! They have %lives% lives left!"
    - "say Second message!"


# What will be executed when the player runs out of lives.
Out-of-Lives:
  ban-on-death: false
  kick-on-death: false
  change-gamemode-on-death: false
  gamemode: SPECTATOR
  teleport-player-world: false
  world: "world"