name: PeligonLifeSteal
version: '${project.version}'
main: net.peligon.LifeSteal.Main
api-version: 1.18
authors: [ darkwinged ]
description: This is an open-source plugin
softdepend: [ Vault ]
commands:
  pellives:
    aliases:
      - plifesteal
      - plives
    description: Allows admins to reload configuration files
  lifesteal:
    description: Allows admins manage player lifes
  lives:
    description: Allows players to view lives
  combattag:
    aliases:
      - ct
    description: Allows players to view how long left they have in combat
  bounty:
    aliases:
      - bounties
    description: Allows players to view their bounty
  heart:
    description: Allows admins to give hearts to players