files:
  - source: '*.yml'
    ignore:
      - '*.java'
      - '*.xml'
      - plugin.yml
      - .gitignore
      - LICENSE
      - TODO.txt
      - '*.md'
      - config.yml
      - Peligon-Enchants
      - Peligon-Teams
      - Peligon-Staff
      - Peligon-Core
      - worth.yml
      - signs.yml
      - pouches.yml
      - coupons.yml
      - Inventories
      - cache.yml
      - customItems.yml
      - items.yml
    translation: /%original_path%/%locale_with_underscore%
