name: PeligonEnchants
version: '${project.version}'
main: net.peligon.PeligonEnchants.Main
api-version: 1.18
authors: [ darkwinged ]
description: This is an open-source plugin
softdepend: [Vault]
commands:
  enchants:
    description: Allows users to enchant their items through a GUI