#######################################################################################
#
#       Welcome to Peligon Teams configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################
Storage:
  # Visit 'plugins/PeligonTeams/Lang/' to see the supported languages.
  lang: "en_US"

Channels-Format:
  Team: "&7[&eTeam&7] &f%player%&f: &f%message%"
  Ally: "&7[&5Ally&7] &f%player%&f: &f%message%"
  Truce: "&7[&bTruce&7] &f%player%&f: &f%message%"
  Moderator: "&7[&2Mod&7] &f%player%&f: &f%message%"

###############################################################
# +---------------------------------------------------------+ #
# |                   Peligon Teams (Teams)                 | #
# |    This is where you can manage settings about teams    | #
# +---------------------------------------------------------+ #
###############################################################
request-timeout: 120

# Check for plugin updates.
check-for-updates: true