#######################################################################################
#
#       Welcome to Peligon Teams configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################
Storage:
  # Visit 'plugins/PeligonTeams/Lang/' to see the supported languages.
  lang: "en_US"
  # Available options: "MySQL", "SQLite"
  database: "SQLite"
  database-settings:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""

###############################################################
# +---------------------------------------------------------+ #
# |                   Peligon Teams (Teams)                 | #
# |    This is where you can manage settings about teams    | #
# +---------------------------------------------------------+ #
###############################################################
Teams-Settings:
  # If this is set to 0 then it will be disabled.
  creation-fee: 0
  starter-vaults: 1
  maximum-vaults: 5
  vault-settings:
    # max-vault-size: "54", multiple of 9
    size: 36
    title: "&eVault &f#%vault_number%"
    # Only moderators or the leader can open the vault.
    # !! Will only work on first vault.
    secured: true


###############################################################
# +---------------------------------------------------------+ #
# |                   Peligon Teams (Items)                 | #
# |    This is where you can manage all custom items that   | #
# |    are used in the plugin.                              | #
# +---------------------------------------------------------+ #
###############################################################
Items:
  # Placeholder Key -------------
  # %amount% - Shows how much the item holds.
  # %transaction% - Generates a random ID.
  # %player% - Gets the players name.
  # %display_player% - Gets the players display name. e.g "[DEVELOPER] Peligon"
  # -----------------------------
  withdraw-experience:
    item: EXPERIENCE_BOTTLE
    name: "&5Experience"
    lore:
      - "&7(Right-Click) to redeem the &aexperience&7."
      - "&7Withdrawn by &e%player%&7."
      - ""
      - "&7Value: &a%amount%"

# Check for plugin updates.
check-for-updates: true