name: PeligonTeams
version: '${project.version}'
main: net.peligon.Teams.Main
api-version: 1.18
authors: [ darkwinged ]
description: This is an open-source plugin
commands:
  team:
    description: Allows players to talk to other players in their team.