#######################################################################################
#
#       Welcome to Peligon Playtime's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/Playtime/Lang/' to see the supported languages.
  Language File: "en_US"
  # Available options: "MySQL", "SQLite"
  database: "SQLite"
  MySQL:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""

format: "%seconds%s, %minutes%m, %hours%hrs, %days%d, %weeks%wks"
leaderboard:
  players: 10
  format: "%position%. &e%player% &f- &a%time_played%"

rewards:
  1:
    # The amount of seconds before the reward is given.
    time: 3600
    message:
      chat: "&aYou have been rewarded for playing for 1 hour!"
      title: "&aYou have been rewarded!"
      subtitle: "&aYou have been rewarded for playing for 1 hour!"
      title-fade-in: 20
      title-stay: 60
      title-fade-out: 20
    commands:
      - "give %player% diamond 1"
      - "eco give %player% 100"
    # This will keep track how many times the player has been rewarded.
    claimed: []
  2:
    time: 86400
    message:
      chat: "&aYou have been rewarded for playing for 1 day!"
      title: "&aYou have been rewarded!"
      subtitle: "&aYou have been rewarded for playing for 1 day!"
      title-fade-in: 20
      title-stay: 60
      title-fade-out: 20
    commands:
      - "give %player% diamond 3"
      - "eco give %player% 1000"
    claimed: []
  3:
    time: 604800
    message:
      chat: "&aYou have been rewarded for playing for 1 week!"
      title: "&aYou have been rewarded!"
      subtitle: "&aYou have been rewarded for playing for 1 week!"
      title-fade-in: 20
      title-stay: 60
      title-fade-out: 20
    commands:
      - "give %player% diamond 5"
      - "eco give %player% 5000"
    claimed: []

check-for-updates: true