name: PeligonPlayTime
version: '${project.version}'
main: net.peligon.PeligonPlayTime.Main
api-version: 1.18
authors: [ darkwinged ]
description: This is an open-source plugin
commands:
  pelplaytime:
    aliases:
      - pplaytime
      - pptime
    description: Allows admins to reload configuration files
  playtime:
    aliases:
      - tplayed
      - timeplayed
    description: Allows players to see how much time they have played on the server
  timeplayedtop:
    aliases:
      - tplayedtop
      - playtimetop
    description: Gives players a list of players with the most time played