#######################################################################################
#
#       Welcome to Peligon Stats's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonStats/Lang/' to see the supported languages.
  Language File: "en_US"
  database: "SQLite"

# What level and experience should everyone start at.
Starting-Level: 0
Starting-Experience: 0

Skills:
  acrobatics:
    enabled: true
    # If you wish to cap the skill maximum do it here.
    # !! -1 for no max level
    maximum-level: -1
    # Disable earning experience in certain worlds.
    disable-worlds: []
    # How much experience the player can earn when doing a task.
    earnable-experience:
      minimum: 25
      maximum: 75
  alchemy:
    enabled: true
    maximum-level: -1
    disable-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75
  excavation:
    enabled: true
    maximum-level: -1
    disable-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75
  fishing:
    enabled: true
    maximum-level: -1
    disable-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75
  herbalism:
    enabled: true
    maximum-level: -1
    disable-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75
  lumberjack:
    enabled: true
    maximum-level: -1
    disable-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75
  mining:
    enabled: true
    maximum-level: -1
    disable-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75
  repair:
    enabled: true
    maximum-level: -1
    disable-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75
  smelting:
    enabled: true
    maximum-level: -1
    disabled-worlds: []
    earnable-experience:
      minimum: 25
      maximum: 75

# How do you want the leaderboard to look.
Stats-Leaderboard:
  players: 10
  format: "%position%. &e%player% &f- &e%level%|%experience%"