#######################################################################################
#
#       Welcome to Peligon Enhanced Storage's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does not have database support.
#
#######################################################################################
Storage:
  # Visit 'plugins/PeligonEnhancedStorage/Lang/' to see the supported languages.
  lang: "en_US"

###############################################################
# +---------------------------------------------------------+ #
# |        Peligon Enhanced Storage (Default Settings)      | #
# |    This is where you can change the default settings    | #
# |    of the plugin and how it will perform.               | #
# +---------------------------------------------------------+ #
###############################################################
defaults:
  player-vault-title: "&ePrivate Vault &8(%number%)"

###############################################################
# +---------------------------------------------------------+ #
# |           Peligon Enhanced Storage (Backpacks)          | #
# |    This is where you can change settings for the        | #
# |    backpack(s) and how they look.                       | #
# +---------------------------------------------------------+ #
###############################################################
Backpacks:
  enabled: true
  normal-settings:
    small:
      # Must be multiples of 9 (Minimum is 9 | Maximum is 54)
      size: 9
      title: "&eSmall Backpack"
    medium:
      size: 18
      title: "&eMedium Backpack"
    large:
      size: 36
      title: "&eLarge Backpack"
    massive:
      size: 54
      title: "&eMassive Backpack"
  adventure-backpack-settings:
    beginner:
      inventory:
        # Must be multiples of 9 (Minimum is 9 | Maximum is 54)
        size: 27
        title: "&7Beginner Adventurer Backpack"
      # Will certain items be restricted from going inside the
      # backpack.
      filtering: true
      # When a player picks up an item will it automatically go
      # inside the backpack.
      automatic-pickup: true
      # Allow players to grab food from their backpack without
      # actually going inside it.
      keep-food-restocked: false
    experienced:
      invetory:
        size: 54
        title: "&5Experienced Adventurer Backpack"
      filtering: true
      automatic-pickup: true
      keep-food-restocked: true









###############################################################
# +---------------------------------------------------------+ #
# |            Peligon Enhanced Storage (Backpack)          | #
# |    This is where you can change settings and how the    | #
# |    backpack will look in the game.                      | #
# +---------------------------------------------------------+ #
###############################################################
Backpack:
  item: Chest
  name: "&e&lBackpack &7(Click)"
  lore:
    - "&7You will never lose your backpack!"
    - ""
    - "&5&lContents"
    - "%contents%"
  number-of-contents: 5
  # Will generate a list of items in the backpack.
  contents-lore-format: "&e ▎ &f%item% &7(x%amount%)"
  more-contents: "&8More..."

Backpack-Inventory:
  title: "&e&lBackpack &7(%player%)"
  # This has to be multiple of 9.
  # minimum : 9 || maximum : 54
  size: 54
  # Change how the item is displayed.
  show-item:
    name: "&f&l%item%"
    hide-attributes: true
    hide-enchants: true
    lore:
      - ""
      - "&e&lInformation"
      - " &e&l▎ &fAmount Stored &e%amount%"
      - " &e&l▎ &fStacks Available &e%stacks%"
      - ""
      - "&aLeft Click for Withdraw Options"
      - "   &cRight Click to Dispose Item"

# Check for plugin updates.
check-for-updates: true