#######################################################################################
#
#       Welcome to Peligon Enhanced Storage's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does not have database support.
#
#######################################################################################
Storage:
  # Visit 'plugins/PeligonEnhancedStorage/Lang/' to see the supported languages.
  lang: "en_US"

###############################################################
# +---------------------------------------------------------+ #
# |        Peligon Enhanced Storage (Default Settings)      | #
# |    This is where you can change the default settings    | #
# |    of the plugin and how it will perform.               | #
# +---------------------------------------------------------+ #
###############################################################
defaults:
  player-vault-title: "&ePrivate Vault &8(%number%)"

# Check for plugin updates.
check-for-updates: true

###############################################################
# +---------------------------------------------------------+ #
# |           Peligon Enhanced Storage (Backpacks)          | #
# |    This is where you can change settings for the        | #
# |    backpack(s) and how they look.                       | #
# +---------------------------------------------------------+ #
###############################################################
Backpacks:
  enabled: true
  normal-settings:
    small:
      # Must be multiples of 9 (Minimum is 9 | Maximum is 54)
      size: 9
      # The title that will be shown when the player opens the backpack.
      title: "&eSmall Backpack"
    medium:
      size: 18
      title: "&eMedium Backpack"
    large:
      size: 36
      title: "&eLarge Backpack"
    massive:
      size: 54
      title: "&eMassive Backpack"
  adventure-settings:
    beginner:
      inventory:
        size: 27
        title: "&7Beginner Adventurer Backpack"
      # Will certain items be restricted from going inside the
      # backpack.
      filtering: true
      # When a player picks up an item will it automatically go
      # inside the backpack.
      automatic-pickup: true
      # Allow players to grab food from their backpack without
      # actually going inside it.
      keep-food-restocked: false
    experienced:
      inventory:
        size: 54
        title: "&5Experienced Adventurer Backpack"
      filtering: true
      automatic-pickup: true
      keep-food-restocked: true
  miners-settings:
    inventory:
      size: 18
      title: "&6Miner Backpack"
    automatic-pickup: true