#######################################################################################
#
#       Welcome to Peligon Enhanced Storage's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################
Storage:
  # Visit 'plugins/PeligonEnhancedStorage/Lang/' to see the supported languages.
  lang: "en_US"
  # Available options: "MySQL", "SQLite"
  database: "SQLite"
  database-settings:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""

###############################################################
# +---------------------------------------------------------+ #
# |            Peligon Enhanced Storage (Section)           | #
# |    [NOTE or Description]                                | #
# +---------------------------------------------------------+ #
###############################################################
Backpack:
  item: Chest
  name: "&aBackpack"
  lore:
    - "&7You will never lose your backpack!"
    - ""
    - "&eContents"
    - "%contents%"
  # Will generate a list of items in the backpack.
  contents-lore-format: "&e ▎ &f%item% &7[ %amount% ]"

defaults:
  player-vault-title: "&ePrivate Vault &8[ %number% &8]"

# Check for plugin updates.
check-for-updates: true