name: PeligonEnhancedStorage
version: '${project.version}'
main: net.peligon.EnhancedStorage.Main
api-version: 1.13
authors: [ darkwinged ]
description: This is an open-source plugin.
commands:
  peligon:
    aliases:
      - pel
    description: Allows admins to view all available peligon plugins.
  playervault:
    aliases:
      - pv
      - vault
    description: Allows players to store items in a private vault.


  pelstorage:
    aliases:
      - pelehancedstorage
      - plgstorage
      - plgenchancedstorage
    description: Allows admins to reload configration files.
