#######################################################################################
#
#       Welcome to Mini Peligon JoinLeaveMessage's configuration, This is where you can
#       change basic settings that will affect how the plugin preforms.
#       As this plugin is a mini plugin, The configuration will be small as there is
#       only one main feature to the plugin.
#
#######################################################################################
# Disable join and/or leave messages altogether.
disable-join-message: false
disable-leave-message: false

# A join/leave message will only be sent if the player has the following permission;
# 'Peligon.JoinLeave.VIP.join' and 'Peligon.JoinLeave.VIP.leave' respectively.
requires-permission: false

# When a new player join a server it will welcome them and show the following count;
counter: 0

messages:
  first-join-message: "&eWelcome %player% to the server! &6(%count%)"
  join-message: "&e%player% has joined the server"
  leave-message: "&c%player% has left the server"