#######################################################################################
#
#       Welcome to Peligon Core's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonCore/Lang/' to see the supported languages.
  Language File: "en_US"
  database: "SQLite"

Disposal-Inventory-Name: "&7Disposal"

# This is a list of commands that players can not perform.
Blocked-Commands:
  - "/bukkit:"
  - /?
  - /help
  - /ver
  - /version
  - /pl
  - /plugins
  - /minecraft:help
  - /minecraft:me
  - /me

Warnings:
  Tool-Durability:
    # percentage of tool durability at which a warning will be displayed.
    percentage:
      - 100
      - 75
      - 50
      - 25
      - 10
      - 5
    sound:
      enabled: true
      id: BLOCK_ANVIL_FALL # pre 1.13.2 use ( ANVIL_LAND )
      volume: 1.0
      pitch: 1.0

Nether-Water: false

World-Protection:
  blacklisted-worlds: []
  events:
    Block-Break: true
    Block-Place: true
    Item-Pickup: true
    Item-Drop: true
    Interact: true
    Redstone: true
    Explosions: true
    Fall-Damage: true
    Player-Damage: true
    Mob-Damage: true
    Mpb-Spawning: true
    Animal-Spawning: true
    Xp-Drop: true