#######################################################################################
#
#       Welcome to Peligon Core's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonCore/Lang/' to see the supported languages.
  Language File: "en_US"
  database: "SQLite"

Disposal-Inventory-Name: "&7Disposal"