name: PeligonCore
version: '${project.version}'
main: net.peligon.PeligonCore.Main
api-version: 1.18
authors: [ darkwinged ]
description: This is an open-source plugin
commands:
  # ADMIN COMMANDS
  pelcore:
    aliases:
      - pcore
    description: Allows admins to reload configuration files
  gamemode:
    aliases:
      - gm
    description: Allows admins to change the gamemode of a player
  gmsurvival:
    aliases:
      - gms
    description: Sets the gamemode of a player to survival
  gmcreative:
    aliases:
      - gmc
    description: Sets the gamemode of a player to creative
  gmadventure:
    aliases:
      - gma
    description: Sets the gamemode of a player to adventure
  gmspectator:
    aliases:
      - gmsp
    description: Sets the gamemode of a player to spectator
  setspawn:
    description: Allows admins to set the spawn
  setwarp:
    description: Allows admins to set a warp
  deletewarp:
    aliases:
      - delwarp
    description: Allows admins to delete a warp
  day:
    description: Allows admins to set the time to day
  night:
    description: Allows admins to set the time to night
  noon:
    description: Allows admins to set the time to noon
  time:
    description: Allows admins to set the time
  weather:
    description: Allows admins to set the weather
  difficulty:
    description: Allows admins to set the difficulty
  fly:
    description: Allows players to set their fly mode
  godmode:
    aliases:
      - god
    description: Allows admins to set be invincible
  # UTILITY COMMANDS
  spawn:
    description: Teleports a player to spawn
  warps:
    description: Shows the player a lists of all warps
  warp:
    description: Allows players to teleport to a warp
  craft:
    description: Allows players to craft items
  disposal:
    description: Allows players to dispose of items
  enderchest:
    description: Allows players to open an enderchest
  playertime:
    aliases:
      - ptime
    description: Allows players to set their own time
  playerweather:
    aliases:
      - pweather
    description: Allows players to set their own weather
  playerday:
    aliases:
      - pday
    description: Allows players to set their own time to day
  playernight:
    aliases:
      - pnight
    description: Allows players to set their own time to night
  playernoon:
    aliases:
      - pnoon
    description: Allows players to set their own time to noon
  # FUN COMMANDS
  hat:
    description: Allows players to wear a hat
  heal:
    description: Allows players to heal themselves
  feed:
    description: Allows players to feed themselves
  suicide:
    description: Allows players to end their lives


