#######################################################################################
#Welcome to Mini Peligon ServerInformation's configuration, This is where you can change
#Basic settings that will affect how the plugin preforms.
#As this plugin is a mini plugin, The configuration will be small as there is
#only one main feature to the plugin.
#######################################################################################
Blocks-Broken: 0
Blocks-Placed: 0
