#######################################################################################
#
#       Welcome to Mini Peligon BlockedCommands configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#       As this plugin is a mini plugin, The configuration will be small as there is
#       only one main feature to the plugin.
#
#######################################################################################
Storage:
  # Visit 'Plugins/PeligonBlockedCommands/Lang/' to see the supported languages.
  Language File: "en_US"

blocked-commands:
  - "/plugins"
  - "/pl"
  - "/help"
  - "/Bukkit:"
  - "/minecraft:"

# This will automatically check for updates
check-for-updates: true
