#######################################################################################
#
#       Welcome to Peligon Economy's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonPlaytime/Lang/' to see the supported languages.
  lang: "en_US"
  # Available options: "File", "MySQL", "SQLite"
  database: "File"
  MySQL:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""
  # Should cash be treated as a physical item?
  physical: false

Accounts:
  banks:
    enabled: true
    options:
      # Set a limit on how much money can be stored in a bank.
      bank-limit: -1
      transaction-log:
        add: "&a+ &6$%amount%&7, &e%recorded% ago &7by &e%player%"
        remove: "&c- &6$%amount%&7, &e%recorded% ago &7by &e%player%"
        # Set a limit on how much can be shown at once.
        limit: 5
      interest:
        # Set the interest rate for banks.
        percentage: 2.0
        # The maximum amount of money the interest will affect
        # Abbreviations: K = Thousand, M = Million, B = Billion, T = Trillion
        maximum: "1M"
        # Time before the interest applies
        # Details: s = Seconds, m = Minutes, h = Hours, d = Days
        time: "24h"
        #time: "15d, 12h, 30m, 30s"

  new-accounts:
    # Set the starting balance for new accounts.
    starting-cash-balance: 100.0
    # Set the starting balance for new bank accounts.
    starting-bank-balance: 0

# This will automatically check for updates
check-for-updates: true

























Economy-Leaderboard:
  cash:
    players: 10
    format: "%position%. &e%player% &f- &2$%amount%"
    show-server-total: true
  bank:
    players: 10
    format: "%position%. &e%player% &f- &2$%amount%"
    show-server-total: true

Sell-GUI:
  # When the player performs the /sell command, the GUI will be opened.
  enabled: true

Items:
  # Placeholder Key -------------
  # %uses% - Required for them to work.
  # -----------------------------
  sell-wand:
    item: DIAMOND_HOE
    name: "&eSell Wand"
    lore:
      - "&7(Right-Click) on chest"
      - "&7 to sell its content!"
      - ""
      - "&7Uses: &a%uses%"

Modules:
  sell-wand: true
  bounties: true
  ATMs: true
  gift-items: true

# Block certain items from being gifted.
Gift-Blacklisted-Items:
  - BEDROCK

# When players die, this will cause them to lose money.
# !! If they do not have enough cash this will automatically use their bank.
Death-Penalty:
  enabled: true
  amount: 100

# Give players a chance to find money inside of grass.
Grass-Scavenge:
  # Be careful as players
  enabled: false
  disabled-plants: []
  disabled-worlds: []
  money:
    1:
      # The amount found.
      amount: 10
      # The chance is treated as a percentage.
      chance:
        minimum: 80
        maximum: 100
    2:
      amount: 35
      chance:
        minimum: 65
        maximum: 75

# Give players a chance to find money when mining.
# !! This only woks with stone blocks.
Mining-Rewards:
  enabled: false
  disabled-worlds: []
  disabled-blocks: []
  money:
    1:
      # The amount found.
      amount: 100
      # The chance is treated as a percentage.
      chance:
        minimum: 80
        maximum: 100
    2:
      amount: 300
      chance:
        minimum: 65
        maximum: 75

# When mining a block, this will give players a chance to find something extra.
# !! This only works with stone blocks.
Lucky-Blocks:
  enabled: false
  disabled-worlds: []
  disabled-blocks: []
  blocks:
    1:
      # The block that will spawn when mined.
      type: BEACON
      chance:
        minimum: 10
        maximum: 12
      commands:
        - "give @p diamond_pickaxe 1"


# !! All bounties will be erased if the plugin is disabled or server is offline.
Bounties:
  # Minimum amount of kills before getting a bounty.
  minimum-kill-streak: 3
  # Amount added to bounty after each kill.
  amount: 50.0

# When a monster or animal is killed you are able to get a reward.
Mob-Rewards:
  money-drop-types:
    # Type of mob
    CHICKEN:
      # If you want to disable any mob drops
      enable: true
      # How much is given to the player
      reward: 5
    PIG:
      enable: true
      reward: 10
    COW:
      enable: true
      reward: 20

# TODO - REDO SERVER GOALS ======================================================
# Setup some server wide goals and give players rewards.
Server-Goals:
  targets:
    First_Goal:
      goal: 10000
      # This data should not be messed with.
      data:
        # Any completed target will be ignored.
        completed: false
        raised: 0
        contributors: []
      # Rewards will only be given out to contributor to the goal.
      rewards:
        - "%econ% 10000"
        - "%item% diamond 5"
        - "%message% &aThanks for reaching the goal!"
        - "%command% say goal reached!"
    Second_Goal:
      goal: 100000
      data:
        completed: false
        raised: 0
        contributors: []
      rewards:
        - "%econ% 10000"
        - "%item% diamond 5"
        - "%message% &aThanks for reaching the goal!"
        - "%command% say goal reached!"
# TODO - END SERVER GOALS ======================================================

# Daily tasks for a player to complete.
daily-tasks:
  '1':
    # The task name.
    name: "&aDaily Task 1"
    # The task description.
    description: "&fYou must &acollect&f 10 &fblocks of &astone&f."
    # Available options: "collect", "break", "place", "kill", "craft", "use", "smelt", "enchant", "tame", "sheer"
    Action: "collect"
    # What block/entity to collect.
    type: "STONE"
    # The task reward.
    reward:
      - "%econ% 10000"
      - "%item% diamond 5"
      - "%message% &aThanks for reaching the goal!"
      - "%command% say goal reached!"
  '2':
    name: "Daily Task 2"
    description: "&fYou must &achop&f 10 &fblocks of &aoak logs&f."
    Action: "break"
    type: "OAK_LOG"
    reward:
      - "%econ% 10000"
      - "%item% diamond 5"
      - "%message% &aThanks for reaching the goal!"
      - "%command% say goal reached!"
  '3':
    name: "Daily Task 3"
    description: "&fYou must &akill&f 10 &asheep&f."
    Action: "kill"
    type: "SHEEP"
    reward:
      - "%econ% 10000"
      - "%item% diamond 5"
      - "%message% &aThanks for reaching the goal!"
      - "%command% say goal reached!"