name: PeligonEconomy
version: '${project.version}'
main: net.peligon.PeligonEconomy.Main
api-version: 1.18
authors: [ darkwinged ]
description: This is an open-source plugin.
depend: [Vault]
softdepend: [PlaceholderAPI, ProtocolLib]
load: STARTUP
loadbefore: [Vault]
commands:
  economy:
    aliases:
      - eco
    description: Allows admins manage player accounts
  pelecon:
    aliases:
      - pecon
      - peconomy
    description: Allows admins to reload configuration files
  balance:
    aliases:
      - bal
      - money
      - coins
    description: Allows users to check their balance
  atm:
    aliases:
      - bank
    description: Allows users to manage their bank accounts
  balancetop:
    aliases:
      - baltop
      - moneytop
    description: Allow users to see who has the most money
  bounty:
    description: Allows users to set bounties on peoples head
  sell:
    aliases:
      - sellall
    description: Allows users to sell all items inside of their inventory
  sellhand:
    description: Allows users to sell all items that is in thir hand
  autosell:
    description: Allows users to automatically sell their items
  chestsell:
    description: Allows users to sell things inside of chests with a command
  sellwand:
    description: Allows users to sell items inside of chests with an item
  pay:
    description: Allows users to transfer money to each other
  withdraw:
    description: Allows users to withdraw money
  experience:
    aliases:
      - xp
      - exp
    description: Allows users to see how much experience they have
  experienceBottle:
    aliases:
      - xpbottle
      - bottle
    description: Allows users to withdraw experience
  daily:
    description: Allows users to get a daily reward
#  gift:
#    description: Allows users to gift items to other players
#  box:
#    aliases:
#      - giftbox
#    description: Allows users to view their gift box
  pouches:
    description: Allows admins to give players pouches