name: PeligonServerInformation
version: '${project.version}'
main: net.peligon.ServerInformation.Main
api-version: 1.19
authors: [ darkwinged ]
commands:
  serverinfo:
    aliases:
      - serverinformation
    description: Shows information about the server