#######################################################################################
#
#       Welcome to Peligon Social's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonSocial/Lang/' to see the supported languages.
  Language File: "en_US"
  # Options 'MYSQL, MongoDB, NONE ( Will use files )'
  database: "MongoDB"

# This will automatically check for updates
check-for-updates: true