#######################################################################################
#
#       Welcome to Peligon Prison's configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/PeligonPrison/Lang/' to see the supported languages.
  Language File: "en_US"
  database: "SQLite"

# How long someone has to accept or deny a request before it expires.
invite-timeout: 30

# Executed when a player gains a new rank.
Rankup:
  message: true
  title-message:
    enabled: true
    title: "&aRankup"
    subtitle: "&aCongratulations!"
    fade-in: 20
    stay: 60
    fade-out: 20

# Executed when a player gains a new prestige.
Prestige:
  message: true
  title-message:
    enabled: true
    title: "&aPrestige"
    subtitle: "&aCongratulations!"
    fade-in: 20
    stay: 60
    fade-out: 20
